In [57]:
import random
import numpy as np 
import pandas as pd
import math

np.set_printoptions(suppress=True)

In [58]:
models = []

In [59]:
sub2 = pd.read_csv('submission2.csv')

In [60]:
sub2

id  genre
0          1  short
1          2  short
2          3  short
3          4  short
4          5  short
...      ...    ...
54195  54196  short
54196  54197  short
54197  54198  short
54198  54199  short
54199  54200  short

[54200 rows x 2 columns]

In [61]:
m0 = pd.read_csv('predict_proba0.csv')
m1 = pd.read_csv('predict_proba1.csv')
m2 = pd.read_csv('predict_proba2.csv')
m3 = pd.read_csv('predict_proba3.csv')
m4 = pd.read_csv('predict_proba4.csv')

In [89]:
m0.values[1]

array([0.00199846, 0.00053844, 0.00102989, 0.00039635, 0.00031971,
       0.01610859, 0.00075797, 0.0062297 , 0.9507552 , 0.000642  ,
       0.00015858, 0.00002649, 0.00022366, 0.0029577 , 0.0002136 ,
       0.00037921, 0.00163455, 0.00007548, 0.00024265, 0.00544356,
       0.00018402, 0.00723177, 0.00007126, 0.00022207, 0.00114686,
       0.0004107 , 0.0006015 ])

In [88]:
m1.values[1]

array([0.0015891 , 0.00087802, 0.0002586 , 0.0004936 , 0.00003886,
       0.02853703, 0.00102174, 0.00230745, 0.9425706 , 0.00075344,
       0.00009731, 0.00004334, 0.00018111, 0.00251801, 0.00001973,
       0.00020907, 0.00024071, 0.00004772, 0.00004088, 0.00600834,
       0.00016939, 0.0045727 , 0.00003535, 0.00010545, 0.00605278,
       0.00003227, 0.00117741])

In [86]:
av1 = np.max([m0, m1], axis = 0)

In [90]:
av1[1]

array([0.00199846, 0.00087802, 0.00102989, 0.0004936 , 0.00031971,
       0.02853703, 0.00102174, 0.0062297 , 0.9507552 , 0.00075344,
       0.00015858, 0.00004334, 0.00022366, 0.0029577 , 0.0002136 ,
       0.00037921, 0.00163455, 0.00007548, 0.00024265, 0.00600834,
       0.00018402, 0.00723177, 0.00007126, 0.00022207, 0.00605278,
       0.0004107 , 0.00117741])

In [82]:
a = np.argmax(av1, axis = 1)
a

array([ 8,  8,  7, ...,  5,  7, 21], dtype=int64)

In [33]:
train_df = pd.read_csv('train.csv')

In [35]:
train_df.genre

0              drama
1           thriller
2              adult
3              drama
4              drama
            ...     
54209         comedy
54210         horror
54211    documentary
54212         comedy
54213        history
Name: genre, Length: 54214, dtype: object

In [36]:
Y = pd.get_dummies(train_df.genre)
CLASS_NUM = Y.shape[1]

In [42]:
Y.columns[21]

'short'